name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_ENV: test

jobs:

  client-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: ['18']
        os: [ubuntu-latest]

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: â™»ï¸ Check out Git Repository
        uses: actions/checkout@v3

      - name: ğŸ”–  Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # https://github.com/bahmutov/npm-install
      # GitHub Action for install npm dependencies with caching without any configuration
      - name: "ğŸ“¦ Install Dependencies"
        uses: bahmutov/npm-install@v1

      - name: ğŸ”´ Lint all files
        run: yarn run lint

      - name: ğŸ— Build
        run: yarn run build

      - name: âœ…  Run tests
        run: yarn test