# GitHub Repository Secrets Needed
# NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
# NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
name: Netlify Deploy

on:
  push:
    branches: [ master ]
    paths:
      - src/**
      - content/**
      - static/**
  workflow_dispatch:
    branches: [ master ]

jobs:
  netlify_deploy:
    runs-on: ubuntu-latest    
    environment:
      name: deployment
      url: https://spencerlepine.com

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: ğŸ”§ Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # https://github.com/bahmutov/npm-install
    # GitHub Action for install npm dependencies with caching without any configuration
    - name: "ğŸ“¦ Install Dependencies"
      uses: bahmutov/npm-install@v1

    - name: "ğŸ“¦ Install Dependencies"
      # if: steps.yarn-cache.outputs.cache-hit != 'true' # Over here!
      run: yarn

    - name: ğŸ— Build
      run: yarn run build

    - name: ğŸš€ Netlify Deploy
      # uses: jsmrcaga/action-netlify-deploy@v1.7.1

      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: netlify deploy --prod