name: ðŸš« Typo Scan

on:
  workflow_dispatch:
  push:

jobs:
  # Preform typo scan
  # https://github.com/crate-ci/typos
  # https://crates.io/crates/typos-cli
  typo_scan:
    name: "ðŸš« Typo Scan"
    runs-on: ubuntu-latest
      
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3
      
      - name:  ðŸ› ï¸ Configure rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: ðŸ› ï¸ Configure rust cargo (package manager)
        if: always()
        uses: actions-rs/cargo@v1
    
      - name: ðŸ“¦ Install spell-checker dependency
        run: cargo install typos-cli
        
      - name: ðŸ› ï¸ Create spell checker config file
        run: |
          touch _typos.toml
          echo "[files]" >> _typos.toml
          echo "extend-exclude = ['public/**']" >> _typos.toml

      - name: ðŸš« Preform typo scan
        id: typo-scan
        run: |
          # ${{ github.workspace }}/../../../.cargo/bin/typos >> typos/typos.txt || true
          echo '## Detected Typos Diff' >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> typos/typos-diff.md
          ${{ github.workspace }}/../../../.cargo/bin/typos --diff >> $GITHUB_STEP_SUMMARY || true
          echo '```' >> typos/typos-diff.md
